### ISSUE TITLE
The game could not be completed due to the wrong position of the last two elements.

### ISSUE THREAD

**Issue by ThatPham2000** [md-siam/flutter_puzzle_hack#1]
I used your library. It is very nice, but I could not complete the game because of the wrong position of the last two elements. Thanks for your help.
https://user-images.githubusercontent.com/57900109/161176993-de9bec6c-90e8-49ae-9ea0-24bd3aff9eb1.png

**Comment by md-siam** [comment]
![Screen Shot 2022-04-01 at 11 48 52 PM](https://user-images.githubusercontent.com/21225918/161315851-c84d5340-0761-45f0-8d10-c59e36be3799.png)

**Comment by md-siam** [comment]
I just solved it.!!
