### ISSUE TITLE
App freezes in between

### ISSUE THREAD

**Issue by preteambuy** [md-siam/flutter_puzzle_hack#2]
Hi, when i play the game, the app freezes for few seconds in between and its happening often. Have u faced the issue?

**Comment by md-siam** [comment]
There is an issue with **Safari** browser. 
Use Google chrome or Firefox browser.

**Comment by preteambuy** [comment]
This happens in the IOS app.

**Comment by md-siam** [comment]
![darkMode](https://user-images.githubusercontent.com/21225918/165312720-87fee195-de49-4f3f-8729-c5353ed829de.gif)

It runs smoothly on iPhone Simulator & Android Emulator

**Comment by md-siam** [comment]
I need more information [preteambuy](https://github.com/preteambuy)
